-- integrity test validation
select
    p.CATEGORY,
    s.SUPPLIER_NAME,
    f.SHIPMENT_ID,
    f.INSPECTION_STATUS,
    f.SHIPPING_COST
from SUPPLY_CHAIN_DW.FACT_SHIPMENTS f
join SUPPLY_CHAIN_DW.DIM_PRODUCTS p on f.PRODUCT_ID = p.PRODUCT_ID
join SUPPLY_CHAIN_DW.DIM_SUPPLIER_DATA s on f.PRODUCT_ID = s.PRODUCT_ID
WHERE f.INSPECTION_STATUS = 'Fail'
FETCH first 10 rows only;

SELECT DISTINCT INSPECTION_STATUS FROM SUPPLY_CHAIN_DW.FACT_SHIPMENTS;

-- analytic work
-- lead time performance(operational analytics)
select
    s.SUPPLIER_NAME,
    p.CATEGORY,
    f.SHIPMENT_ID,
    s.LEAD_TIME_DAYS AS PROMISED_DAYS,
    (f.DELIVERY_DATE-f.SHIP_DATE) AS ACTUAL_DAYS,
    CASE
        WHEN (f.DELIVERY_DATE - f.SHIP_DATE) <= s.LEAD_TIME_DAYS THEN 'On Time'
        ELSE 'Delayed'
    END as PERFORMANCE_STATUS
FROM SUPPLY_CHAIN_DW.FACT_SHIPMENTS f
JOIN SUPPLY_CHAIN_DW.DIM_SUPPLIER_DATA s on f.PRODUCT_ID = s.PRODUCT_ID
JOIN SUPPLY_CHAIN_DW.DIM_PRODUCTS p on f.PRODUCT_ID = p.PRODUCT_ID
FETCH FIRST 20 rows only;
--.........................

-- summary stats comparing averages by category
SELECT 
    p.CATEGORY,
    ROUND(AVG(f.SHIPPING_COST), 2) AS MEAN_COST,
    ROUND(VARIANCE(f.SHIPPING_COST), 2) AS VAR_COST,
    COUNT(f.SHIPMENT_ID) AS SAMPLE_SIZE
FROM SUPPLY_CHAIN_DW.FACT_SHIPMENTS f
JOIN SUPPLY_CHAIN_DW.DIM_PRODUCTS p ON f.PRODUCT_ID = p.PRODUCT_ID
WHERE p.CATEGORY IN ('Electronics', 'Textiles', 'Automotive', 'Medical Supplies')
GROUP BY p.CATEGORY;

-- f-test comparing consistency
SELECT 
    s.SUPPLIER_NAME,
    VARIANCE(f.DELIVERY_DATE - f.SHIP_DATE) AS LEAD_TIME_VARIANCE
FROM SUPPLY_CHAIN_DW.FACT_SHIPMENTS f
JOIN SUPPLY_CHAIN_DW.DIM_SUPPLIER_DATA s ON f.PRODUCT_ID = s.PRODUCT_ID
GROUP BY s.SUPPLIER_NAME
fetch first 20 rows only;
