-- granting the permission
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SESSION TO SUPPLY_CHAIN_DW;

-- allow to store the 15k+ rows
ALTER USER SUPPLY_CHAIN_DW QUOTA UNLIMITED ON USERS;

SELECT table_name FROM all_tables WHERE owner = 'SUPPLY_CHAIN_DW';

-- to see the rows 
SELECT * FROM SUPPLY_CHAIN_DW.STG_SHIPMENTS
FETCH FIRST 50 ROW ONLY;
-- see the whole table
SELECT * FROM SUPPLY_CHAIN_DW.STG_PRODUCTS;
-- to see the columns
DESCRIBE SUPPLY_CHAIN_DW.STG_SHIPMENTS;
-- to see the total rows count
SELECT COUNT(*) AS total_records FROM SUPPLY_CHAIN_DW.STG_SHIPMENTS;

-- data cleaning 
-- checking the duplicates
SELECT PRODUCT_ID, COUNT(*)
FROM SUPPLY_CHAIN_DW.STG_PRODUCTS
GROUP BY PRODUCT_ID
HAVING COUNT(*)>1;

-- checking for nulls
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN SHIPPING_COST IS NULL THEN 1 ELSE 0 END) AS missing_cost,
    SUM(CASE WHEN QUANTITY IS NULL THEN 1 ELSE 0 END ) as missing_quantity,
    SUM(CASE WHEN SHIP_DATE IS NULL THEN 1 ELSE 0 END) as missing_ship_dates,
    SUM(CASE WHEN DELIVERY_DATE IS NULL THEN 1 ELSE 0 END) as missing_delivery_dates
FROM SUPPLY_CHAIN_DW.STG_SHIPMENTS;

-- converting the dates formate from large text to date
SELECT
    SHIPMENT_ID,
    SHIPPING_COST,
    QUANTITY,
    TO_DATE(DBMS_LOB.SUBSTR(SHIP_DATE, 20,1),'YYYY-MM-DD') AS ship_date_text
FROM SUPPLY_CHAIN_DW.STG_SHIPMENTS
FETCH FIRST 10 ROWS ONLY;

-- checking for outliers
SELECT * FROM SUPPLY_CHAIN_DW.STG_SHIPMENTS
WHERE SHIPPING_COST <=0 OR QUANTITY <= 0;

SELECT * FROM SUPPLY_CHAIN_DW.STG_INSPECTIONS
FETCH FIRST 10 ROWS ONLY;

SELECT * FROM SUPPLY_CHAIN_DW.STG_SUPPLIER_DATA
WHERE LEAD_TIME_DAYS <=0 OR NEGOTIATED_RATE <= 0;

-- checking for table name 
DESCRIBE SUPPLY_CHAIN_DW.STG_SHIPMENTS

-- converting the clob to text changing data type
SELECT
    SHIPMENT_ID,
    CAST(DBMS_LOB.SUBSTR(INSPECTION_STATUS,50,1) AS VARCHAR2(50)) AS STATUS,
    CAST(DBMS_LOB.SUBSTR(DEFECT_TYPE,100,1) AS VARCHAR2(100)) AS DEFECT
FROM SUPPLY_CHAIN_DW.STG_INSPECTIONS
FETCH FIRST 10 ROWS ONLY;


SELECT
    PRODUCT_ID,
    UNIT_COST,
    CAST(DBMS_LOB.SUBSTR(CATEGORY,100,1) AS VARCHAR2(100)) AS CATEGORY
FROM SUPPLY_CHAIN_DW.STG_PRODUCTS
FETCH FIRST 10 ROWS ONLY;

SELECT
    LOCATION_ID,
    CAST(DBMS_LOB.SUBSTR(CITY, 100,1) AS VARCHAR2(100)) AS LOCATIONS,
    CAST(DBMS_LOB.SUBSTR(COUNTRY,100,1) AS VARCHAR2(100)) AS COUNTRIES
FROM SUPPLY_CHAIN_DW.STG_LOCATIONS
FETCH FIRST 10 ROWS ONLY;

DESCRIBE SUPPLY_CHAIN_DW.STG_INSPECTIONS

-- changing the data types
-- creating the temp tables
ALTER TABLE SUPPLY_CHAIN_DW.STG_INSPECTIONS
ADD (STATUS_TEMP VARCHAR2(50), DEFECT_TEMP VARCHAR2(100));

-- converting and copying the faulty table data in temp table
UPDATE SUPPLY_CHAIN_DW.STG_INSPECTIONS
SET STATUS_TEMP = DBMS_LOB.SUBSTR(INSPECTION_STATUS, 50,1),
DEFECT_TEMP = DBMS_LOB.SUBSTR(DEFECT_TYPE,100,1);
COMMIT;

-- dropping the old tables
ALTER TABLE SUPPLY_CHAIN_DW.STG_INSPECTIONS
DROP (INSPECTION_STATUS,DEFECT_TYPE);

-- renaming the new temp tables to the old tables
ALTER TABLE SUPPLY_CHAIN_DW.STG_INSPECTIONS
RENAME COLUMN STATUS_TEMP TO INSPECTION_STATUS;

ALTER TABLE SUPPLY_CHAIN_DW.STG_INSPECTIONS
RENAME COLUMN DEFECT_TEMP TO DEFECT_TYPE;

-- ...............
DESCRIBE SUPPLY_CHAIN_DW.STG_SHIPMENTS
-- creating new temp table
ALTER TABLE SUPPLY_CHAIN_DW.STG_SHIPMENTS
ADD(SHIP_DATE_TEMP DATE, DELIVERY_DATE_TEMP DATE);

-- altering and moving the values to the new
UPDATE SUPPLY_CHAIN_DW.STG_SHIPMENTS
SET
    SHIP_DATE_TEMP = TO_DATE(DBMS_LOB.SUBSTR(SHIP_DATE, 10,1), 'YYYY-MM-DD'),
    DELIVERY_DATE_TEMP = TO_DATE(DBMS_LOB.SUBSTR(DELIVERY_DATE,10,1), 'YYYY-MM-DD');
COMMIT;

-- drop the old clob
ALTER TABLE SUPPLY_CHAIN_DW.STG_SHIPMENTS
DROP (SHIP_DATE, DELIVERY_DATE)

-- renaming the temp tables
ALTER TABLE SUPPLY_CHAIN_DW.STG_SHIPMENTS
RENAME COLUMN SHIP_DATE_TEMP TO SHIP_DATE;

ALTER TABLE SUPPLY_CHAIN_DW.STG_SHIPMENTS
RENAME COLUMN DELIVERY_DATE_TEMP TO DELIVERY_DATE;

SELECT COUNT(SHIP_DATE) FROM SUPPLY_CHAIN_DW.STG_SHIPMENTS;
SELECT * FROM SUPPLY_CHAIN_DW.STG_SHIPMENTS
FETCH FIRST 10 ROWS ONLY;
-- ......................
DESCRIBE SUPPLY_CHAIN_DW.STG_LOCATIONS

ALTER TABLE SUPPLY_CHAIN_DW.STG_LOCATIONS
ADD(CITY_TEMP VARCHAR2(100), COUNTRY_TEMP VARCHAR2(100), REGION_TEMP VARCHAR2(100));

UPDATE SUPPLY_CHAIN_DW.STG_LOCATIONS
SET
    CITY_TEMP = DBMS_LOB.SUBSTR(CITY, 100,1),
    COUNTRY_TEMP = DBMS_LOB.SUBSTR(COUNTRY,100,1),
    REGION_TEMP = DBMS_LOB.SUBSTR(REGION,100,1);
COMMIT;

ALTER TABLE SUPPLY_CHAIN_DW.STG_LOCATIONS
DROP (CITY,COUNTRY,REGION);

ALTER TABLE SUPPLY_CHAIN_DW.STG_LOCATIONS
RENAME COLUMN CITY_TEMP TO CITY;

ALTER TABLE SUPPLY_CHAIN_DW.STG_LOCATIONS
RENAME COLUMN COUNTRY_TEMP TO COUNTRY;

ALTER TABLE SUPPLY_CHAIN_DW.STG_LOCATIONS
RENAME COLUMN REGION_TEMP TO REGION;

SELECT * FROM SUPPLY_CHAIN_DW.STG_LOCATIONS
FETCH FIRST 10 ROWS ONLY;
--......................

DESCRIBE SUPPLY_CHAIN_DW.STG_PRODUCTS

ALTER TABLE SUPPLY_CHAIN_DW.STG_PRODUCTS
ADD(CATEGORY_TEMP VARCHAR2(100));

UPDATE SUPPLY_CHAIN_DW.STG_PRODUCTS
SET
    CATEGORY_TEMP = DBMS_LOB.SUBSTR(CATEGORY ,100,1);
COMMIT;

ALTER TABLE SUPPLY_CHAIN_DW.STG_PRODUCTS
DROP(CATEGORY);

ALTER TABLE SUPPLY_CHAIN_DW.STG_PRODUCTS
RENAME COLUMN CATEGORY_TEMP TO CATEGORY;

SELECT * FROM SUPPLY_CHAIN_DW.STG_PRODUCTS
FETCH FIRST 10 ROWS ONLY;
-- ......................

DESCRIBE SUPPLY_CHAIN_DW.STG_SUPPLIER_DATA;

ALTER TABLE SUPPLY_CHAIN_DW.STG_SUPPLIER_DATA
ADD (SUPPLIER_NAME_TEMP VARCHAR2(100));

UPDATE SUPPLY_CHAIN_DW.STG_SUPPLIER_DATA
SET
    SUPPLIER_NAME_TEMP = DBMS_LOB.SUBSTR(SUPPLIER_NAME,100,1);
COMMIT;

ALTER TABLE SUPPLY_CHAIN_DW.STG_SUPPLIER_DATA
DROP(SUPPLIER_NAME);

ALTER TABLE SUPPLY_CHAIN_DW.STG_SUPPLIER_DATA
RENAME COLUMN SUPPLIER_NAME_TEMP TO SUPPLIER_NAME;

SELECT * FROM SUPPLY_CHAIN_DW.STG_SUPPLIER_DATA
FETCH FIRST 10 ROWS ONLY;
--..................

DESCRIBE SUPPLY_CHAIN_DW.STG_SUPPLIER_DATA;

-- checking the inconsistency
SELECT CITY, COUNT(*) FROM SUPPLY_CHAIN_DW.STG_LOCATIONS
GROUP by CITY
ORDER BY CITY;
--..............